# Generated by Django 5.1.6 on 2025-03-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_parentuploadedresult_semester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='approval_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
